# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug_x86
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x86)
  Glad_config = debug_x86
  ImGui_config = debug_x86
  Assimp_config = debug_x86
  Vortex_config = debug_x86
  GameProject_config = debug_x86
  VortexEditor_config = debug_x86
endif
ifeq ($(config),debug_x64)
  Glad_config = debug_x64
  ImGui_config = debug_x64
  Assimp_config = debug_x64
  Vortex_config = debug_x64
  GameProject_config = debug_x64
  VortexEditor_config = debug_x64
endif
ifeq ($(config),debug_arm)
  Glad_config = debug_arm
  ImGui_config = debug_arm
  Assimp_config = debug_arm
  Vortex_config = debug_arm
  GameProject_config = debug_arm
  VortexEditor_config = debug_arm
endif
ifeq ($(config),debug_arm64)
  Glad_config = debug_arm64
  ImGui_config = debug_arm64
  Assimp_config = debug_arm64
  Vortex_config = debug_arm64
  GameProject_config = debug_arm64
  VortexEditor_config = debug_arm64
endif
ifeq ($(config),release_x86)
  Glad_config = release_x86
  ImGui_config = release_x86
  Assimp_config = release_x86
  Vortex_config = release_x86
  GameProject_config = release_x86
  VortexEditor_config = release_x86
endif
ifeq ($(config),release_x64)
  Glad_config = release_x64
  ImGui_config = release_x64
  Assimp_config = release_x64
  Vortex_config = release_x64
  GameProject_config = release_x64
  VortexEditor_config = release_x64
endif
ifeq ($(config),release_arm)
  Glad_config = release_arm
  ImGui_config = release_arm
  Assimp_config = release_arm
  Vortex_config = release_arm
  GameProject_config = release_arm
  VortexEditor_config = release_arm
endif
ifeq ($(config),release_arm64)
  Glad_config = release_arm64
  ImGui_config = release_arm64
  Assimp_config = release_arm64
  Vortex_config = release_arm64
  GameProject_config = release_arm64
  VortexEditor_config = release_arm64
endif
ifeq ($(config),dist_x86)
  Glad_config = dist_x86
  ImGui_config = dist_x86
  Assimp_config = dist_x86
  Vortex_config = dist_x86
  GameProject_config = dist_x86
  VortexEditor_config = dist_x86
endif
ifeq ($(config),dist_x64)
  Glad_config = dist_x64
  ImGui_config = dist_x64
  Assimp_config = dist_x64
  Vortex_config = dist_x64
  GameProject_config = dist_x64
  VortexEditor_config = dist_x64
endif
ifeq ($(config),dist_arm)
  Glad_config = dist_arm
  ImGui_config = dist_arm
  Assimp_config = dist_arm
  Vortex_config = dist_arm
  GameProject_config = dist_arm
  VortexEditor_config = dist_arm
endif
ifeq ($(config),dist_arm64)
  Glad_config = dist_arm64
  ImGui_config = dist_arm64
  Assimp_config = dist_arm64
  Vortex_config = dist_arm64
  GameProject_config = dist_arm64
  VortexEditor_config = dist_arm64
endif

PROJECTS := Glad ImGui Assimp Vortex GameProject VortexEditor

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C Vortex/thirdParty/Glad -f Makefile config=$(Glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Vortex/thirdParty/imgui -f Makefile config=$(ImGui_config)
endif

Assimp:
ifneq (,$(Assimp_config))
	@echo "==== Building Assimp ($(Assimp_config)) ===="
	@${MAKE} --no-print-directory -C Vortex/thirdParty/Assimp -f Makefile config=$(Assimp_config)
endif

Vortex: Glad Assimp ImGui
ifneq (,$(Vortex_config))
	@echo "==== Building Vortex ($(Vortex_config)) ===="
	@${MAKE} --no-print-directory -C Vortex -f Makefile config=$(Vortex_config)
endif

GameProject: Vortex Glad Assimp ImGui
ifneq (,$(GameProject_config))
	@echo "==== Building GameProject ($(GameProject_config)) ===="
	@${MAKE} --no-print-directory -C GameProject -f Makefile config=$(GameProject_config)
endif

VortexEditor: Vortex Glad Assimp ImGui
ifneq (,$(VortexEditor_config))
	@echo "==== Building VortexEditor ($(VortexEditor_config)) ===="
	@${MAKE} --no-print-directory -C VortexEditor -f Makefile config=$(VortexEditor_config)
endif

clean:
	@${MAKE} --no-print-directory -C Vortex/thirdParty/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C Vortex/thirdParty/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Vortex/thirdParty/Assimp -f Makefile clean
	@${MAKE} --no-print-directory -C Vortex -f Makefile clean
	@${MAKE} --no-print-directory -C GameProject -f Makefile clean
	@${MAKE} --no-print-directory -C VortexEditor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x86"
	@echo "  debug_x64"
	@echo "  debug_arm"
	@echo "  debug_arm64"
	@echo "  release_x86"
	@echo "  release_x64"
	@echo "  release_arm"
	@echo "  release_arm64"
	@echo "  dist_x86"
	@echo "  dist_x64"
	@echo "  dist_arm"
	@echo "  dist_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Glad"
	@echo "   ImGui"
	@echo "   Assimp"
	@echo "   Vortex"
	@echo "   GameProject"
	@echo "   VortexEditor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"